### ISSUE TITLE
Infografia de realidad aumentada

### ISSUE THREAD

**Issue by IsraelMerlyn** [SistemasTecTlaxiaco/infografia-IsraelMerlyn#1]
[Realidad Aumentada Infografías (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-IsraelMerlyn/files/6198568/Realidad.Aumentada.Infografias.1.pdf)

**Comment by hiuta** [comment]
Calificacion : 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
